#!/bin/bash
# Pipe input to emacs through a temporary file
args=''

# Start emacs daemon if necessary
if ! emacsclient -ca false -e '(delete-frame)' ; then
    emacs --daemon
    args='c'
fi

# Process arguments
while [[ $1 ]]
do
    # Start a new frame if the --create option is given
    if [ "$1" == '-c' ] || [ "$1" == '--create' ]; then
        args='c'
    fi
    shift
done
args="-n${args}a ''"

# Create temporary file, open it with emacs, delete it afterwards
TMP=$(mktemp) && cat > $TMP && emacsclient $args $TMP ; rm $TMP
